[GERAL]
MAILCOW_DIR = /opt/mailcow-dockerized
# De quantas em quantas horas o script deve verificar?
INTERVALO_HORAS = 12

[SMTP]
SMTP_SERVER = smtp.seuprovedor.com
SMTP_PORT = 465
SMTP_USER = seu-email@dominio.com.br
SMTP_PASS = sua-senha-aqui
SENDER_NAME = Monitor Mailcow
SENDER_EMAIL = seu-email@dominio.com.br
# Separe os e-mails destinatários por vírgula
RECIPIENT_EMAILS = admin@dominio.com.br, ti@dominio.com.br

[TELEGRAM]
# Insira seu Token e Chat ID para ativar. Deixe vazio para desativar.
# Para múltiplos destinatários, separe os Chat IDs por vírgula.
TELEGRAM_BOT_TOKEN = 1234567890:ABCdefGhIjkLmnopQRstUvwxYz
TELEGRAM_CHAT_ID = 11111111, 22222222
